package com.common.dao;

import com.common.model.UserBasicInfo;
import com.common.model.UserBasicInfoExample;
import com.common.reposity.page.Page;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int countByExample(UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int deleteByExample(UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int insert(UserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int insertSelective(UserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    List<UserBasicInfo> selectByExample(UserBasicInfoExample example);
    List<UserBasicInfo> selectLimitByExample(UserBasicInfoExample example,Page page);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") UserBasicInfo record, @Param("example") UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_info
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    int updateByExample(@Param("record") UserBasicInfo record, @Param("example") UserBasicInfoExample example);
}