package com.common.model;

import java.util.Date;

public class UserBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.user_id
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.user_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.real_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.user_type
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.user_state
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private String userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.create_date
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_info.user_password
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.user_id
     *
     * @return the value of user_basic_info.user_id
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.user_id
     *
     * @param userId the value for user_basic_info.user_id
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.user_name
     *
     * @return the value of user_basic_info.user_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.user_name
     *
     * @param userName the value for user_basic_info.user_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.real_name
     *
     * @return the value of user_basic_info.real_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.real_name
     *
     * @param realName the value for user_basic_info.real_name
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.user_type
     *
     * @return the value of user_basic_info.user_type
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.user_type
     *
     * @param userType the value for user_basic_info.user_type
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.user_state
     *
     * @return the value of user_basic_info.user_state
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.user_state
     *
     * @param userState the value for user_basic_info.user_state
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setUserState(String userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.create_date
     *
     * @return the value of user_basic_info.create_date
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.create_date
     *
     * @param createDate the value for user_basic_info.create_date
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_info.user_password
     *
     * @return the value of user_basic_info.user_password
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_info.user_password
     *
     * @param userPassword the value for user_basic_info.user_password
     *
     * @mbggenerated Sun Sep 25 18:42:03 GMT+08:00 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
}